BATCH_SIZE = 200
CRITIC_LOSS_COEF = 1.0
ENTROPY_LOSS = 1e-3
LOSS_CLIPPING = 0.2
LR = 0.0003
NUM_SGD_ITER = 4
MAX_GRAD_NORM = 5.0
SUMMARY = False
VF_CLIP = 5.0

CNN_SHARE_LAYERS = True
MLP_SHARE_LAYERS = False
